# Generated by Django 4.1.1 on 2022-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('email1', models.EmailField(max_length=254)),
                ('password', models.EmailField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
